# -*- coding: utf-8 -*-
"""fuel_efficiency_deployement.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VllEF_I4YT4RbypGU784Ol8bbLSi0Yca
"""

import streamlit as st
import joblib
import numpy as np

# Load trained model
model = joblib.load("fuel_efficiency_model.pkl")

st.set_page_config(page_title="Fuel Efficiency Predictor", layout="centered")

st.title("🚗 Vehicle Fuel Efficiency Predictor")
st.write("Predict MPG (Miles Per Gallon) using Linear Regression")

# User Inputs
cylinders = st.slider("Cylinders", 3, 8, 4)
displacement = st.slider("Displacement", 50.0, 500.0, 150.0)
horsepower = st.slider("Horsepower", 40.0, 250.0, 100.0)
weight = st.slider("Weight", 1500.0, 5000.0, 2500.0)
acceleration = st.slider("Acceleration", 8.0, 25.0, 15.0)
model_year = st.slider("Model Year", 70, 82, 76)
origin = st.slider("Origin (1=USA, 2=Europe, 3=Japan)", 1, 3, 1)

# Predict button
if st.button("Predict MPG"):
    input_data = np.array([[cylinders, displacement, horsepower,
                            weight, acceleration, model_year, origin]])

    prediction = model.predict(input_data)

    st.success(f"Estimated Fuel Efficiency: {prediction[0]:.2f} MPG 🚀")
